# PhysicsConfig.gd
extends Node

# World / Environment
const WORLD_SIZE = 512.0
const WORLD_HALF_SIZE = 256.0
const WORLD_SPAWN_MARGIN = 20.0
const C = 800.0

# Gravity System
const G_CONSTANT = 0.1
const G_CURVATURE_SENSITIVITY = 0.2
const G_FORCE_SCALE = 1000.0
const G_ITERATIONS = 3
const G_GRID_SIZE = 16
const G_VISUAL_DISTORTION = 3.0

# Player
const PLAYER_DEFAULT_MASS = 125.0
const PLAYER_THRUST = 10000.0
const PLAYER_ROT_SPEED = 4
const PLAYER_LASER_RECOIL_MOMENTUM = 1000.0
const PLAYER_LASER_COOLDOWN = 3.0
const PLAYER_SPAWN_TIMER = 5.0
const PLAYER_GRAVITY_EPS = 2.0

# Asteroid
const ASTEROID_MASS_DEFAULT = 250.0
const ASTEROID_GRAVITY_EPS = 32.0
const ASTEROID_SHATTER_VEL_MIN = 50.0
const ASTEROID_SHATTER_VEL_MAX = 150.0
const ASTEROID_SHATTER_RADIUS = 12.0
const ASTEROID_INVINCIBILITY_FRAMES = 3
const ASTEROID_INITIAL_WEIGHT_TOTAL = 1500.0

# Laser
const LASER_SPEED = C
const LASER_ENERGY_DEFAULT = 1000.0
const LASER_TRAIL_LIFETIME = 0.6
const LASER_GRAVITY_DEFLECTION_SCALE = 75.0
const LASER_GRAVITY_EPS = 8.0
