services:
  - type: web
    name: asteroids-signaling
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 8080
